apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  certSANs:
  - "10.0.48.1"
  - "10.0.48.115"
  - "10.0.48.116"
  - "master115"
  - "master116"
controlPlaneEndpoint: "10.0.48.1:6443"
etcd:
    external:
        endpoints:
        - http://10.0.48.112:2379
        - http://10.0.48.113:2379
        - http://10.0.48.114:2379
networking:
  serviceSubnet: "10.2.0.0/16"
  podSubnet: "10.1.0.0/16"
controllerManager:
  extraArgs:
    "node-cidr-mask-size": "22"
kubernetesVersion: "v1.25.4"
